version: '3'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama  
    volumes:
      - ollama_data:/root/.ollama
    pull_policy: always
    restart: unless-stopped
    ports:
      - "11434:11434"
    networks:
      - app-network

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: open-webui-backend
    volumes:
      - backend_data:/app/backend/data
    depends_on:
      - ollama
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=your_secret_key_here
      - ENV=dev
    networks:
      - app-network
    restart: unless-stopped

volumes:
  ollama_data: {}
  backend_data: {}

networks:
  app-network:
    driver: bridge 